
<div ng-controller="main" ng-init="setTab({
        name: 'Unidad de negocio',
        classIcon: 'fa fa-suitcase'
      })">
</div>
<div ng-controller="UnidadNegocioController" class="container">

	<a href="#" ng-click="changeLanguaje('es')">{{'LANGS.ES' | translate}}</a>
	<a href="#" ng-click="changeLanguaje('en')">{{'LANGS.EN' | translate}}</a>
	<a href="#" ng-click="changeLanguaje('pt')">{{'LANGS.PT' | translate}}</a>
	<div class="catalog-title-group row" style="padding:0;margin:0">
		<div class="col-md-6 col-sm-7 col-xs-12">
			<h3 style="padding:0;margin:0">{{ 'UNIDAD_NEGOCIO.TITLE' | translate}}</h3>
		</div>
	</div>
</div>

