<div ng-controller="main" ng-init="setTab({
        name: 'Origen Venta',
        classIcon: 'fa fa-suitcase'
      })">
</div>
<div ng-controller="OrigenVentaController" class="container">

	<a href="#" ng-click="changeLanguaje('es')">{{'LANGS.ES' | translate}}</a>
	<a href="#" ng-click="changeLanguaje('en')">{{'LANGS.EN' | translate}}</a>
	<a href="#" ng-click="changeLanguaje('pt')">{{'LANGS.PT' | translate}}</a>
	<div class="catalog-title-group row" style="padding:0;margin:0">
		<div class="col-md-6 col-sm-7 col-xs-12">
			<h3 style="padding:0;margin:0">{{ 'ORIGEN_VENTA.TITLE' | translate}}</h3>
		</div>
		<div class="col-md-3 col-sm-5 col-xs-12 pull-right">
			<div class="input-group group-input-search">
				<span class="icon-input-search" id="search-corporativo">
					<i class="fa fa-search"></i>
				</span>
				<input type="text" class="form-control input-search" ng-model="searchOrigenVenta" aria-describedby="search-corporativo" ng-keyup="tableOrigenVenta.filter({ $: searchOrigenVenta })" placeholder="{{'ACTIONS.SEARCH' | translate}}...">
				<span class="input-group-btn">
					<button class="btn btn-gray" type="button" style="border-radius:50%" ng-click="getOrigenesVenta()">
						<i class="fa fa-refresh {{searchingOrigenesVenta ? 'fa-spin' : ''}}"></i>
					</button>
				</span>
				<span class="input-group-btn">
					<button class="btn btn-primary" type="button" style="border-radius:50%" data-toggle="modal" data-target="#modalCorporativo" ng-click="prepareCreationOrigenVenta()">
						<i class="fa fa-plus"></i>
					</button>
				</span>
			</div>
		</div>
	</div>
	<br>

	<div loading-container="tableOrigenVenta.settings().$loading" ng-init="getOrigenesVenta()">
		<table class="table table-condensed" ng-table="tableOrigenVenta">
			<tbody>
				<tr ng-repeat="origen in $data" ng-dblclick="prepareUpdatingOrigenVenta(origen)">
					<td width="1">
						<a href="#" class="icon-float-hover" ng-click="prepareDeleteOrigenVenta(origen.id_origen_venta)">
							<i class="fa fa-trash"></i>
						</a>
					</td>
					<td data-title="'NAME' | translate" sortable="'nombre_corporativo'" ng-if="cols.nombre_origen_venta.show">
						{{origen.origen_venta}}
					</td>
				</tr>
				<tr ng-show="!origenesVenta.length">
					<td>{{'TABLES.NO_RESULTS_FOUND' | translate}}</td>
				</tr>
			</tbody>
		</table>
	</div>

	<!--Star Modal Origen Venta -->
	<div class="modal face dark-modal" id="modalOrigenVenta" tabindex="-1" role="dialog" aria-labelledby="ModalCorporativo">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">
						<i class="fa fa-circle"></i>
					</span></button>
					<h4 class="modal-title" id="ModalCorporativo">{{isCreating ? 'Crear' : 'Editar'}} origen de venta</h4>
				</div>
				<div class="modal-body">
					<div class="row">
						<form ng-submit="optionSubmitOrigenVenta()">
							<div class="col-md-12">
								<input type="text" class="dark-form" placeholder="Origen de venta" ng-model="origenVenta.origen_venta" required maxlength="30">
							</div>
							<div class="col-md-12">
								<button class="btn btn-blue btn-modal-submit pull-right">{{isCreating ? 'Crear' : 'Actualizar'}}
								</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div><!-- End Modal Origen Venta -->

	<!-- Star Modal Delete Origen Venta  -->
	<div class="modal fade dark-modal" id="modalDeleteOrigenVenta" tabindex="-1" role="dialog" aria-labelledby="ModalOrigenVenta">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">
						<i class="fa fa-circle"></i>
					</span></button>
					<h4 class="modal-title" id="ModalOrigenVenta">¿Esta seguro de borrar el Origen de Venta?</h4>
				</div>
				<div class="modal-body no-padding-modal-body">
					<button type="button" class="btn btn-default" data-dismiss="modal"> Cancelar</button>
					 <button type="button" class="btn btn-danger" ng-click="deleteOrigenVenta()">Eliminar</button>
				</div>
			</div>
		</div>
	</div>

</div>
