<div ng-controller="OrigenVentaController">

	<button class="btn btn-default" ng-click="prepareCreationOrigenVenta()">Nuevo</button>
	<table class="table table-condensed" ng-init="getOrigenesVenta()">
		<thead>
			<tr>
				<td>Origen venta</td>
				<td></td>
			</tr>
		</thead>
		<tbody>
			<tr ng-repeat="origen in origenesVenta">
				<td>{{origen.origen_venta}}</td>
				<td>
					<a href="#" ng-click="prepareDeleteOrigenVenta(origen.id_origen_venta)">Eliminar</a>
					<a href="#" ng-click="prepareUpdatingOrigenVenta(origen)">Editar</a>
				</td>
			</tr>
			<tr ng-show="!origenesVenta.length">
				<td>No hay origenes de venta</td>
			</tr>
		</tbody>
	</table>


	<!-- START Modal Corporativo -->
		<div class="modal fade dark-modal" id="modalOrigenVenta" tabindex="-1" role="dialog" aria-labelledby="ModalCorporativo">
		  <div class="modal-dialog" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">
		        	<i class="fa fa-circle"></i>
		        </span></button>
		        <h4 class="modal-title" id="ModalCorporativo">{{isCreating ? 'Crear' : 'Editar'}} origen de venta</h4>
		      </div>
		      <div class="modal-body">
		      	<div class="row">
		      		<form ng-submit="optionSubmitOrigenVenta()">
				      	<div class="col-md-12">
				        	<input type="text" class="dark-form" placeholder="Origen de venta" ng-model="origenVenta.origen_venta" required maxlength="30">
				      	</div>
				      	<div class="col-md-2 col-sm-2 col-xs-6">
				        	<button class="btn btn-blue btn-modal-submit pull-right">{{isCreating ? 'Crear' : 'Actualizar'}}</button>
				      	</div>
		      		</form>
		      	</div>
		      </div>
		    </div>
		  </div>
		</div><!-- END Modal Corporativo -->

	<!-- START Modal DELETE OrigenVenta -->
	<div class="modal fade dark-modal" id="modalDeleteOrigenVenta" tabindex="-1" role="dialog" aria-labelledby="ModalOrigenVenta">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">
	        	<i class="fa fa-circle"></i>
	        </span></button>
	        <h4 class="modal-title" id="ModalOrigenVenta">¿Esta seguro de eliminar el origen de la ventas?<h4>
	      </div>
	      <div class="modal-body no-padding-modal-body">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
	        <button type="button" class="btn btn-danger" ng-click="deleteOrigenVenta()">Eliminar</button>
	      </div>
	    </div>
	  </div>
	</div><!-- END Modal DELETE OrigenVenta -->
</div>
