<?php echo $this->doctype(); ?>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <base href="/">
        <?php echo $this->headTitle($this->translate('Icaav | '))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/logosuite.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/AdminLTE.min.css')
                        ->prependStylesheet($this->basePath() . '/css/skin-blue.css')
                        ->prependStylesheet($this->basePath() . '/css/main.css')
                        ->prependStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->appendFile($this->basePath() . '/js/jquery.min.js')
            ->appendFile($this->basePath() . '/js/bootstrap.min.js')
            ->appendFile($this->basePath() . '/js/app.min.js')
            ->appendFile($this->basePath() . '/js/jquery.slimscroll.min.js')
            ->appendFile($this->basePath() . '/js/angular/lib/angular.min.js')
            ->appendFile($this->basePath() . '/js/angular/lib/ngStorage.js')
            ->appendFile($this->basePath() . '/js/angular/lib/angular-route.js')
            ->appendFile($this->basePath() . '/js/angular/lib/services.js')
            ->appendFile($this->basePath() . '/js/angular/modules/auth/controllers/login.js')
            ->appendFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
    <body class="hold-transition skin-blue sidebar-mini fixed" ng-app="admin">
      <header class="main-header">
        <!-- Logo -->
        <a href="#" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>I</b>W</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>ICAAV</b>web</span>
        </a>

        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- User Account: style can be found in dropdown.less -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <span class="hidden-xs">.</span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                  <li class="user-header">
                  </li>
                  <!-- Menu Body -->
                  <li class="user-body">
                    <div class="col-xs-4 text-center">
                      <a href="#">Informaci&oacute;n</a>
                    </div>
                  </li>
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                      <a href="#" class="btn btn-default btn-flat">Profile</a>
                    </div>
                    <div class="pull-right">
                      <a href="#" class="btn btn-default btn-flat">Sign out</a>
                    </div>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar" ng-controller="main">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <ul class="sidebar-menu">
            <li ng-repeat="m in menu" class="{{m.isActive?'active':''}} treeview">
              <a ng-click="setTab(m)" style="cursor:pointer;">
                <i class="{{m.classIcon}}"></i>
                <span>{{m.name}}</span>
                <i class="{{m.isActive?'fa fa-circle pull-right':''}}" style="color:#2EFE2E;font-size:7px;padding-top:5px"></i>
                <i class="{{(m.li)?'fa fa-angle-left pull-right':''}}"></i>
              </a>
              <ul class="treeview-menu">
                <li ng-repeat="li in m.li">
                  <a href="{{li.url?li.url:''}}" ng-click="setTab(li)">
                    <i class="{{li.classIcon}}"></i>
                    <span>{{li.name}}</span>
                    <i class="{{li.isActive?'fa fa-circle pull-right':''}}" style="color:#2EFE2E;font-size:7px;padding-top:5px"></i>
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </section>
        <!-- /.sidebar -->
      </aside>
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper" style="margin-top:-60px;min-height: 610px;" ng-controller="main">
        <div>
          <ul class="nav nav-tabs tabs-window" role="tablist">
            <li ng-repeat="tab in tabs" role="presentation" class="{{tab.isActive?'active':''}}">
              <a href="{{tab.url}}" ng-click="setTab(tab)" class="content-tabs-window">
                {{tab.name}}
              </a>
                <i class="fa fa-remove pull right close-tab-window" ng-click="removeTab(tab.name)" ng-show="!tab.isActive"></i>
            </li>
          </ul>
        </div>
        <div style="padding-top:15px;">
          <?php //echo $this->content; ?>
          <div ng-view></div>
        </div>
      </div>
      <footer class="main-footer">
        <strong>Copyright &copy; 2016-2017 Inform&aacute;tica Gerencial S.A de C.V.</strong> All rights reserved.
      </footer>

    <script>

    /*angular.module('admin', [])
    .factory('scopes', icaav.services.storageScope)
    .controller('adminC', ['$scope', 'scopes', function($scope, scopes) {
      scope = scope.get('admin');
      if(!scope) {
          $scope.input = 'algo';
          scopes.set('admin', $scope);
      } else {
          $scope = scope.get('admin');
      }

    }]);*/


      angular.module('app', ['ngRoute', 'ngStorage'])
      .controller('CorporativoController', ['$scope', '$http', '$localStorage', '$location', '$timeout', function($scope, $http, $localStorage, $location, $timeout) {

        $scope.httpForm = new icaav.services.HTTPForm($http);
        $scope.location = new icaav.services.Location($location);
        $scope.corporativoEdit = {};
        $scope.vars = $localStorage.$default({
          corporativoAdd: {
            id_corporativo:  '',
            nombre_corporativo: '',
            limite_credito: '',
            estatus_corporativo: false,
          }
        });

        $scope.setDataEditCorportativo = function(corporativo) {
          $scope.corporativoEdit = new Object(corporativo);
          $scope.corporativoEdit.estatus_corporativo = $scope.corporativoEdit.estatus_corporativo == 1;
        };

        $scope.routeAdd = function() {
          $scope.location.path('/admin/corporativo/add');
        };

        $scope.routeView = function() {
          $scope.location.path('/admin/corporativo');
        };

        $scope.getCorporativos = function() {
          $scope.httpForm.post(icaav.helpers.getBasePath() +'/admin/corporativo/get-corporativos', {
            start_pag: 0,
            end_pag: 100
          }).success(function(data) {
            if(data['@pr_affect_rows']) {
              $scope.corporativos = data.results;
              console.log($scope.corporativos);
            }
          });
        };

        $scope.deleteCorporativo = function(id) {
          if(confirm("¿Esta seguro de eliminar el corporativo?")) {
            $scope.httpForm.post(icaav.helpers.getBasePath() + '/admin/corporativo/delete-ajax', {
					id_corporativo: id
             }).success(function(data) {
                 console.log(data);
              if(data['@pr_message'] == 'SUCCESS' && data['@pr_affect_rows']) {
            	  $scope.getCorporativos();
              } else {
                alert('No se pudo eliminar el corporativo');
              }
            });
          }
        };

        $scope.createCorporativo = function() {
          $scope.httpForm.post(icaav.helpers.getBasePath() + '/admin/corporativo/add-ajax', $scope.vars.corporativoAdd)
          .success(function(data) {
            if(data['@pr_message'] == 'SUCCESS' && data['@pr_affect_rows']) {
              $timeout(function() {
                delete $scope.vars.corporativoAdd;
              },0);
              $scope.location.path('/admin/corporativo');
            } else {
              alert('No se pudo crear el corporativo');
            }
          });
        };

        $scope.updateCorporativo = function() {
          $scope.httpForm.post(icaav.helpers.getBasePath() + '/admin/corporativo/edit-ajax', $scope.corporativoEdit)
          .success(function(data) {
            if(data['@pr_message'] == 'SUCCESS' && data['@pr_affect_rows']) {
              $scope.getCorporativos();
              $scope.corporativoEdit = {};
            } else {
              alert('No se pudo editar el corporativo');
            }
          });
        };

    }])
      .config(['$routeProvider', '$locationProvider', function($routeProvider, $locationProvider) {
        var basePath = icaav.helpers.getBasePath();
        $routeProvider
        .when(basePath + '/admin', {templateUrl : basePath + '/admin?terminal=true'})
        .when(basePath + '/admin/corporativo', {templateUrl : basePath + '/admin/corporativo?terminal=true'})
        .when(basePath + '/admin/corporativo/add', {templateUrl : basePath + '/admin/corporativo/add?terminal=true'})
        .when(basePath + '/admin/unidad-negocio', {templateUrl : basePath + '/admin/unidad-negocio?terminal=true'})
        .otherwise({
          templateUrl: window.location.href + '?terminal=true'
        });
        $locationProvider.html5Mode(true);
      }])
      .factory('tabs', function($rootScope) {
          var tabs = [];
          var i    = 0;
          function changeTabs() {
            $rootScope.$broadcast('changeTabs');
          }
          function getTab(name) {
            tab = null;
            for(i in tabs) {
              tabs[i].isActive = false;
              if(tabs[i].name === name) {
                tab = tabs[i];
              }
            }
            return tab;
          }
          return {
            activeTab: null,
            set: function(tab) {
              this.activeTab = getTab(tab.name);
              if(!this.activeTab) {
                this.activeTab = {
                  name: tab.name,
                  url : tab.url,
                  isActive: true,
                  classIcon: tab.classIcon
                };
                tabs.push(this.activeTab);
              } else {
                this.activeTab.isActive = true;
              }
              changeTabs();
            }, remove: function(name) {
              for(i = 0; i < tabs.length; i++) {
                if(tabs[i].name === name) {
                  tabs.splice(i, 1);
                }
              }
              changeTabs();
            }, getTabs: function() {
              return tabs;
            }, getActiveTab: function() {
              return this.activeTab;
            }
          };
      })
      .controller('main', ['$scope', 'tabs', '$location', '$localStorage', function($scope, tabs, $location, $localStorage) {
        var basePath = icaav.helpers.getBasePath();
        $scope.menu = [{
          url: basePath + '/admin',
          name: 'Dashboard',
          classIcon: 'fa fa-dashboard',
        }, {
          name: 'Catálogos',
          classIcon: 'fa fa-files-o',
          li: [{
            name: 'Corporativos',
            url: basePath + '/admin/corporativo',
            classIcon: 'fa fa-suitcase'
          }, {
            name: 'Unidades de negocio',
            url: basePath + '/admin/unidad-negocio',
            classIcon: 'fa fa-user-secret'
          }]
        }];
        $scope.tabs = [];
        $scope.selectedTab = {};

        $scope.$on('changeTabs', function() {
          $scope.tabs = tabs.getTabs();
          $scope.cleanActives(tabs.getActiveTab().name);
        });

        $scope.setDefaultTab = function() {

        };

        $scope.activeMenu = function() {
          for(i in $scope.tabs) {
            if($scope.tabs[i].isActive) {
              for(j in $scope.menu) {
                $scope.menu[j].isActive = false;
                if($scope.tabs[i].name === $scope.menu[j].name) {
                  $scope.menu[j].isActive = true;
                  $scope.selectedTab = $scope.menu[j];
                }
              }
            }
          }
        };

        $scope.cleanActives = function(nameTabSelect) {
          for(i in $scope.menu) {
            if($scope.menu[i].li) {
              for(j in $scope.menu[i].li) {
                $scope.menu[i].li[j].isActive = nameTabSelect == $scope.menu[i].li[j].name;
              }
            } else {
              $scope.menu[i].isActive = nameTabSelect == $scope.menu[i].name;
            }
          }
        }

        $scope.setTab = function(tab) {
          if(tab.url) {
            $location.path(tab.url);
            tabs.set(tab);
          }
        };

        $scope.removeTab = function(name) {
          tabs.remove(name);
        };

      }]);
      angular.module('admin', ['app']);
    </script>
    <script> icaav.helpers.setBasePath("<?php echo $this->basePath()?>"); </script>
    </body>
</html>
