
<div ng-controller="CorporativoController">
	<a href="#" ng-click="routeView()">regresar</a>
	<form ng-submit="createCorporativo()" name="formCreateCorporativo">
		<input type="text" class="form-control" name="id_corporativo" ng-model="vars.corporativoAdd.id_corporativo" placeholder="Clave" required>
		<span ng-show="formCreateCorporativo.id_corporativo.$invalid && formCreateCorporativo.id_corporativo.$touched" class="text-danger">La clave es requerida.</span>
		<input type="text" class="form-control" name="name" ng-model="vars.corporativoAdd.nombre_corporativo" placeholder="Nombre" required>
		<span ng-show="formCreateCorporativo.nombre_corporativo.$invalid && formCreateCorporativo.nombre_corporativo.$touched" class="text-danger">El nombre es requerido.</span>
		<input type="number" step="any" class="form-control" ng-model="vars.corporativoAdd.limite_credito" placeholder="Limite de credito">
		<input type="checkbox" ng-model="vars.corporativoAdd.estatus_corporativo" placeholder="activo">
		<button>Registrar</button>
	</form>
</div>
