<div class="container">
	<div ng-controller="CorporativoController">
		<div class="catalog-title-group row" style="padding:0;margin:0">
			<div class="col-md-6">
				<h3 style="padding:0;margin:0">Cat&aacute;logo de corporativos</h3>
			</div>
			<div class="col-md-6">
				<div class="input-group">
				  <span class="input-group-addon" id="search-corporativo">
				  	<i class="fa fa-search"></i>
				  </span>
				  <input type="text" class="form-control" aria-describedby="search-corporativo">
				  <span class="input-group-btn">
			        <button class="btn btn-primary" type="button" style="border-radius:50%">+</button>
			      </span>
				</div>
			</div>
		</div>
		<div ng-init="getCorporativos()">
			<a href="#" ng-click="routeAdd()">add</a>
			<input ng-model="corp">
			<table class="table">
				<thead>
					<th>Clave</th>
					<th>Nombre</th>
					<th>Limite de credito</th>
				</thead>
				<tbody>
					<tr ng-repeat="corporativo in corporativos | filter:corp">
						<td>{{corporativo.id_corporativo}}</td>
						<td>{{corporativo.nombre_corporativo}}</td>
						<td>{{corporativo.nombre_corporativo}}</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>