<?php 
$title = 'My albums';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('album', array('module'=>'album','action'=>'add'));?>">Add new album</a>
 </p>
 <table class="table">
 <tr>
     <th>Title</th>
     <th>Artist</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($albums as $album) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($album->getTitle());?></td>
     <td><?php echo $this->escapeHtml($album->getArtist());?></td>
     <td>
         <a href="<?php echo $this->url('album',
             array('action'=>'edit', 'id' => $album->getIdAlbum()));?>">Edit</a>
         <a href="<?php echo $this->url('album',
             array('action'=>'delete', 'id' => $album->getIdAlbum()));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>